# Generated by Django 4.2.1 on 2023-05-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='shoename',
            new_name='name',
        ),
    ]
